# permissions for end users to edit veleroes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-editor-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - veleroes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - veleroes/status
  verbs:
  - get
